
var _FunkyKarts = (
function(_FunkyKarts) {
  _FunkyKarts = _FunkyKarts || {};

var g;g||(g=typeof _FunkyKarts !== 'undefined' ? _FunkyKarts : {});String.prototype.startsWith||(String.prototype.startsWith=function(a,b){return this.substr(b||0,a.length)===a});
function aa(){function a(){document.removeEventListener("touchend",a,!1);b.call(window)}function b(){try{this.La=new AudioContext({latencyHint:"balanced",sampleRate:44100})}catch(r){try{this.La=new AudioContext}catch(p){this.La=new webkitAudioContext}}this.Va=this.La.createDynamicsCompressor();this.Va.connect(this.La.destination);this.Wa=this.La.createGain();this.Wa.connect(this.Va);this.Sa=this.La.createGain();this.Sa.connect(this.Va);this.Pa.forEach(function(a,b){this.La.decodeAudioData(a,function(a){this.Pa.set(b,
a)}.bind(this))});if(44100!=this.La.sampleRate)console.log("Unsupported sample rate : "+this.La.sampleRate);else{this.eb=this.La.createScriptProcessor(4096,2,2);this.eb.connect(this.Sa);var a=h(16384),b=h(16384),c=new Float32Array(l.buffer,a,4096),k=new Float32Array(l.buffer,b,4096);window.setTimeout(function(){this.eb.onaudioprocess=function(d){.01<this.Sa.gain.value&&(q(a,b),q(a+2048,b+2048),q(a+4096,b+4096),q(a+6144,b+6144),q(a+8192,b+8192),q(a+10240,b+10240),q(a+12288,b+12288),q(a+14336,b+14336),
d.outputBuffer.getChannelData(0).set(c),d.outputBuffer.getChannelData(1).set(k))}.bind(this)},1E3)}}this.Pa=new Map;var c=navigator.platform.toLowerCase();c.startsWith("iphone")||c.startsWith("ipod")||c.startsWith("ipad")?document.addEventListener("touchend",a,!1):b()}function ba(){this.La&&this.La.suspend()}function ca(){this.La&&this.La.resume()}function da(a){this.La&&(this.Wa.gain.value=a)}function ea(a){this.La&&(this.Sa.gain.value=a)}
function fa(a,b,c){b=t.slice(b,b+c).buffer;this.La?this.La.decodeAudioData(b,function(b){this.Pa.set(a,b);ha(a)}.bind(this)):this.Pa.set(a,b)}function ha(a){if(this.La&&this.Pa.has(a)){var b=this.La.createBufferSource();b.buffer=this.Pa.get(a);b.connect(this.Wa);b.start()}}var v={},x;for(x in g)g.hasOwnProperty(x)&&(v[x]=g[x]);var ia=[],y="",ja;document.currentScript&&(y=document.currentScript.src);y=0!==y.indexOf("blob:")?y.substr(0,y.lastIndexOf("/")+1):"";
ja=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ka=console.log.bind(console),z=console.warn.bind(console);for(x in v)v.hasOwnProperty(x)&&(g[x]=v[x]);v=null;function la(a){ma||(ma={});ma[a]||(ma[a]=1,z(a))}var ma,A;"object"!==typeof WebAssembly&&z("no native wasm support detected");
var na,oa=new WebAssembly.Table({initial:1412,maximum:1412,element:"anyfunc"}),B=!1;function pa(a,b){a||C("Assertion failed: "+b)}var qa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ra(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&qa)return qa.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var e=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|e);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|e<<6|k:(f&7)<<18|e<<12|k<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function D(a,b){return a?ra(t,a,b):""}
function E(a,b,c,d){if(0<d){d=c+d-1;for(var f=0;f<a.length;++f){var e=a.charCodeAt(f);if(55296<=e&&57343>=e){var k=a.charCodeAt(++f);e=65536+((e&1023)<<10)|k&1023}if(127>=e){if(c>=d)break;b[c++]=e}else{if(2047>=e){if(c+1>=d)break;b[c++]=192|e>>6}else{if(65535>=e){if(c+2>=d)break;b[c++]=224|e>>12}else{if(c+3>=d)break;b[c++]=240|e>>18;b[c++]=128|e>>12&63}b[c++]=128|e>>6&63}b[c++]=128|e&63}}b[c]=0}}
function sa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function ta(a){var b=sa(a)+1,c=ua(b);E(a,va,c,b);return c}var wa,va,t,xa,ya,F,za,l,Aa,Ba=33554432;na=new WebAssembly.Memory({initial:Ba/65536,maximum:Ba/65536});wa=na.buffer;Ba=wa.byteLength;var G=wa;wa=G;g.HEAP8=va=new Int8Array(G);g.HEAP16=xa=new Int16Array(G);
g.HEAP32=F=new Int32Array(G);g.HEAPU8=t=new Uint8Array(G);g.HEAPU16=ya=new Uint16Array(G);g.HEAPU32=za=new Uint32Array(G);g.HEAPF32=l=new Float32Array(G);g.HEAPF64=Aa=new Float64Array(G);F[489384]=7200576;function Ca(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.$a;"number"===typeof c?void 0===b.Ra?g.dynCall_v(c):g.dynCall_vi(c,b.Ra):c(void 0===b.Ra?null:b.Ra)}}}var Da=[],Ea=[],Fa=[],Ga=[],Ha=[],Ia=Math.ceil,Ja=Math.floor,H=0,Ka=null,I=null;g.preloadedImages={};
g.preloadedAudios={};function C(a){ka(a);z(a);B=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function La(){var a=J;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var J="demo.wasm";La()||(J=y+J);function Ma(){try{throw"both async and sync fetching of the wasm failed";}catch(a){C(a)}}
function Na(){return"function"===typeof fetch?fetch(J,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+J+"'";return a.arrayBuffer()}).catch(function(){return Ma()}):new Promise(function(a){a(Ma())})}
var Oa={1412509:function(){var a=document.domain,b=sa(a)+1,c=h(b);E(a,t,c,b);return c},1412765:function(){var a=navigator.userAgent.toLowerCase(),b=navigator.platform.toLowerCase();return b?b.startsWith("win")?1:b.startsWith("mac")?2:b.startsWith("android")||"linux armv7l"==b?5:b.startsWith("linux")?a.includes("cros")?4:3:b.startsWith("iphone")||b.startsWith("ipod")||b.startsWith("ipad")||b.startsWith("pike")?6:0:0},1413339:function(){var a=window.document.documentElement;(a.requestFullscreen||a.mozRequestFullScreen||
a.webkitRequestFullScreen||a.msRequestFullscreen).call(a)},1413536:function(a){a=D(a);try{top.location=a}catch(b){}},1413611:function(){var a=window.document,b=!!(a.fullscreenElement||a.mozFullScreenElement||a.webkitFullscreenElement||a.msFullscreenElement),c=window.innerWidth===screen.width&&window.innerHeight===screen.height;return(a.fullscreenEnabled||a.mozFullScreenEnabled||a.webkitFullscreenEnabled||a.msFullscreenEnabled)&&(b||!c)},1414047:function(){var a=window.document;return!!(a.fullscreenElement||
a.mozFullScreenElement||a.webkitFullscreenElement||a.msFullscreenElement)},1414190:function(){var a=window.document;(a.exitFullscreen||a.mozCancelFullScreen||a.webkitExitFullscreen||a.msExitFullscreen).call(a)},1414529:function(a,b){var c=document.querySelector("#display");c.width=a;c.height=b;c.tabIndex=0}},Pa=[];Ea.push({$a:function(){Qa()}});var Ra=[null,[],[]],K=0;function Sa(){K+=4;return F[K-4>>2]}var Ta={};function Ua(){C()}
function Va(a,b){Wa=a;Xa=b;if(L)if(0==a)M=function(){var a=Math.max(0,Ya+b-Ua())|0;setTimeout(N,a)};else if(1==a)M=function(){Za(N)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(a){if("setimmediate"===a.data||"setimmediate"===a.data.target)a.stopPropagation(),c.shift()()},!0);setImmediate=function(a){c.push(a);postMessage("setimmediate","*")}}M=function(){setImmediate(N)}}}
function $a(a,b,c,d,f){A=!0;pa(!L,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");L=a;ab=d;var e="undefined"!==typeof d?function(){g.dynCall_vi(a,d)}:function(){g.dynCall_v(a)};var k=O;N=function(){if(!B)if(0<bb.length){var a=Date.now(),b=bb.shift();b.$a(b.Ra);if(cb){var c=cb,d=0==c%1?c-1:Math.floor(c);cb=b.ob?d:(8*c+(d+.5))/9}console.log('main loop blocker "'+
b.name+'" took '+(Date.now()-a)+" ms");g.setStatus&&(a=g.statusMessage||"Please wait...",b=cb,c=db.rb,b?b<c?g.setStatus(a+" ("+(c-b)+"/"+c+")"):g.setStatus(a):g.setStatus(""));k<O||setTimeout(N,0)}else if(!(k<O))if(eb=eb+1|0,1==Wa&&1<Xa&&0!=eb%Xa)M();else{0==Wa&&(Ya=Ua());a:if(!(B||g.preMainLoop&&!1===g.preMainLoop())){try{e()}catch(u){if(u instanceof fb)break a;u&&"object"===typeof u&&u.stack&&z("exception thrown: "+[u,u.stack]);throw u;}g.postMainLoop&&g.postMainLoop()}k<O||("object"===typeof SDL&&
SDL.audio&&SDL.audio.kb&&SDL.audio.kb(),M())}};f||(b&&0<b?Va(0,1E3/b):Va(1,1),M());if(c)throw"unwind";}var M=null,O=0,L=null,ab=0,Wa=0,Xa=0,eb=0,bb=[],db={},Ya,N,cb,P=!1,gb=!1,hb=[];
function ib(){function a(){gb=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}g.preloadPlugins||(g.preloadPlugins=[]);if(!jb){jb=!0;try{Q=!0}catch(c){Q=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}kb="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:Q?null:console.log("warning: no BlobBuilder");
lb="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;g.cb||"undefined"!==typeof lb||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),g.cb=!0);g.preloadPlugins.push({canHandle:function(a){return!g.cb&&/\.(jpg|jpeg|png|bmp)$/i.test(a)},handle:function(a,b,f,e){var c=null;if(Q)try{c=new Blob([a],{type:mb(b)}),c.size!==a.length&&(c=new Blob([(new Uint8Array(a)).buffer],{type:mb(b)}))}catch(n){la("Blob constructor present but fails: "+
n+"; falling back to blob builder")}c||(c=new kb,c.append((new Uint8Array(a)).buffer),c=c.getBlob());var d=lb.createObjectURL(c),p=new Image;p.onload=function(){pa(p.complete,"Image "+b+" could not be decoded");var c=document.createElement("canvas");c.width=p.width;c.height=p.height;c.getContext("2d").drawImage(p,0,0);g.preloadedImages[b]=c;lb.revokeObjectURL(d);f&&f(a)};p.onerror=function(){console.log("Image "+d+" could not be decoded");e&&e()};p.src=d}});g.preloadPlugins.push({canHandle:function(a){return!g.xb&&
a.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(a,b,f,e){function c(c){p||(p=!0,g.preloadedAudios[b]=c,f&&f(a))}function d(){p||(p=!0,g.preloadedAudios[b]=new Audio,e&&e())}var p=!1;if(Q){try{var n=new Blob([a],{type:mb(b)})}catch(u){return d()}n=lb.createObjectURL(n);var m=new Audio;m.addEventListener("canplaythrough",function(){c(m)},!1);m.onerror=function(){if(!p){console.log("warning: browser could not fully decode audio "+b+", trying slower base64 approach");for(var d="",e=0,f=0,
k=0;k<a.length;k++)for(e=e<<8|a[k],f+=8;6<=f;){var r=e>>f-6&63;f-=6;d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[r]}2==f?(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(e&3)<<4],d+="=="):4==f&&(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(e&15)<<2],d+="=");m.src="data:audio/x-"+b.substr(-3)+";base64,"+d;c(m)}};m.src=n;nb(function(){c(m)})}else return d()}});var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&
b.addEventListener("click",function(a){!gb&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),a.preventDefault())},!1))}}
function ob(a,b,c,d){if(b&&g.Ua&&a==g.canvas)return g.Ua;var f;if(b){var e={antialias:!1,alpha:!1,ab:1};if(d)for(var k in d)e[k]=d[k];if("undefined"!==typeof pb&&(f=qb(a,e)))var r=rb[f].Xa}else r=a.getContext("2d");if(!r)return null;c&&(b||pa("undefined"===typeof R,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),g.Ua=r,b&&sb(f),g.Bb=b,hb.forEach(function(a){a()}),ib());return r}var ub=!1,vb=void 0,S=void 0;
function wb(a,b,c){function d(){P=!1;var a=f.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a?(f.exitFullscreen=xb,vb&&f.requestPointerLock(),P=!0,S?("undefined"!=typeof SDL&&(F[SDL.screen>>2]=za[SDL.screen>>2]|8388608),yb(g.canvas),zb()):yb(f)):(a.parentNode.insertBefore(f,a),a.parentNode.removeChild(a),S?("undefined"!=typeof SDL&&(F[SDL.screen>>2]=za[SDL.screen>>2]&
-8388609),yb(g.canvas),zb()):yb(f));if(g.onFullScreen)g.onFullScreen(P);if(g.onFullscreen)g.onFullscreen(P)}vb=a;S=b;Ab=c;"undefined"===typeof vb&&(vb=!0);"undefined"===typeof S&&(S=!1);"undefined"===typeof Ab&&(Ab=null);var f=g.canvas;ub||(ub=!0,document.addEventListener("fullscreenchange",d,!1),document.addEventListener("mozfullscreenchange",d,!1),document.addEventListener("webkitfullscreenchange",d,!1),document.addEventListener("MSFullscreenChange",d,!1));var e=document.createElement("div");f.parentNode.insertBefore(e,
f);e.appendChild(f);e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?function(){e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(e.webkitRequestFullScreen?function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);c?e.requestFullscreen({Cb:c}):e.requestFullscreen()}
function xb(){if(!P)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Bb=0;function Za(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Bb)Bb=b+1E3/60;else for(;b+2>=Bb;)Bb+=1E3/60;setTimeout(a,Math.max(Bb-b,0))}}function nb(a){A=!0;setTimeout(function(){B||a()},1E4)}
function mb(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}function Cb(a,b,c){ja(a,function(c){pa(c,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(c))},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';})}var Db=[];function zb(){var a=g.canvas;Db.forEach(function(b){b(a.width,a.height)})}
function yb(a,b,c){b&&c?(a.lb=b,a.ib=c):(b=a.lb,c=a.ib);var d=b,f=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/f<g.forcedAspectRatio?d=Math.round(f*g.forcedAspectRatio):f=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var e=Math.min(screen.width/d,screen.height/f);d=Math.round(d*e);f=Math.round(f*
e)}S?(a.width!=d&&(a.width=d),a.height!=f&&(a.height=f),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||f!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",f+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var jb,Q,kb,lb,Ab,Eb=0,Fb=0,Gb=0,Hb=0,Ib=0,Jb=0,Kb=null,Lb=null,Mb=!1;
function Nb(){for(var a=T.length-1;0<=a;--a)Ob(a);T=[];Pb=[]}var Pb=[];function Qb(){if(Rb&&Sb.Ta)for(var a=0;a<Pb.length;++a){var b=Pb[a];Pb.splice(a,1);--a;b.Ab.apply(this,b.nb)}}var Rb=0,Sb=null,T=[];function Ob(a){var b=T[a];b.target.removeEventListener(b.Ma,b.gb,b.Na);T.splice(a,1)}
function U(a){function b(b){++Rb;Sb=a;Qb();a.Qa(b);Qb();--Rb}if(a.Oa)a.gb=b,a.target.addEventListener(a.Ma,b,a.Na),T.push(a),Mb||(Ga.push(Nb),Mb=!0);else for(var c=0;c<T.length;++c)T[c].target==a.target&&T[c].Ma==a.Ma&&Ob(c--)}function Tb(a){return a===a+0?D(a):a}var Ub=[0,document,window];function V(a){return Ub[a]||document.querySelector(Tb(a))}
function Vb(a,b,c,d,f,e){Hb||(Hb=h(256));a={target:V(a),Ma:e,Oa:d,Qa:function(a){a=a||event;var c=a.target.id?a.target.id:"",e=Hb,k=a.target;E(k?k==window?"#window":k==screen?"#screen":k&&k.nodeName?k.nodeName:"":"",t,e+0,128);E(c,t,e+128,128);W(d,f,e,b)&&a.preventDefault()},Na:c};U(a)}
function Wb(a,b,c,d,f,e){Eb||(Eb=h(164));a={target:V(a),Ta:!0,Ma:e,Oa:d,Qa:function(a){a=a||event;var c=Eb;E(a.key?a.key:"",t,c+0,32);E(a.code?a.code:"",t,c+32,32);F[c+64>>2]=a.location;F[c+68>>2]=a.ctrlKey;F[c+72>>2]=a.shiftKey;F[c+76>>2]=a.altKey;F[c+80>>2]=a.metaKey;F[c+84>>2]=a.repeat;E(a.locale?a.locale:"",t,c+88,32);E(a.char?a.char:"",t,c+120,32);F[c+152>>2]=a.charCode;F[c+156>>2]=a.keyCode;F[c+160>>2]=a.which;W(d,f,c,b)&&a.preventDefault()},Na:c};U(a)}
function Xb(a,b,c,d,f,e){Fb||(Fb=h(64));a=V(a);U({target:a,Ta:"mousemove"!=e&&"mouseenter"!=e&&"mouseleave"!=e,Ma:e,Oa:d,Qa:function(c){c=c||event;var e=a,k=Fb;F[k>>2]=c.screenX;F[k+4>>2]=c.screenY;F[k+8>>2]=c.clientX;F[k+12>>2]=c.clientY;F[k+16>>2]=c.ctrlKey;F[k+20>>2]=c.shiftKey;F[k+24>>2]=c.altKey;F[k+28>>2]=c.metaKey;xa[k+32>>1]=c.button;xa[k+34>>1]=c.buttons;var n=c.movementY||c.screenY-Lb;F[k+36>>2]=c.movementX||c.screenX-Kb;F[k+40>>2]=n;e=0>Ub.indexOf(e)?e.getBoundingClientRect():{left:0,top:0};
F[k+44>>2]=c.clientX-e.left;F[k+48>>2]=c.clientY-e.top;"wheel"!==c.type&&"mousewheel"!==c.type&&(Kb=c.screenX,Lb=c.screenY);W(d,f,Fb,b)&&c.preventDefault()},Na:c})}
function Yb(a,b,c,d){Gb||(Gb=h(36));a=V(a);U({target:a,Ma:"resize",Oa:d,Qa:function(c){c=c||event;if(c.target==a){var e=Gb,f=document.body;F[e>>2]=c.detail;F[e+4>>2]=f.clientWidth;F[e+8>>2]=f.clientHeight;F[e+12>>2]=innerWidth;F[e+16>>2]=innerHeight;F[e+20>>2]=outerWidth;F[e+24>>2]=outerHeight;F[e+28>>2]=pageXOffset;F[e+32>>2]=pageYOffset;W(d,10,e,b)&&c.preventDefault()}},Na:c})}
function Zb(a,b,c,d,f,e){Jb||(Jb=h(1684));a=V(a);U({target:a,Ta:"touchstart"==e||"touchend"==e,Ma:e,Oa:d,Qa:function(c){c=c||event;for(var e={},k=0;k<c.touches.length;++k){var n=c.touches[k];n.Ya=!1;e[n.identifier]=n}for(k=0;k<c.changedTouches.length;++k)n=c.changedTouches[k],e[n.identifier]=n,n.Ya=!0;for(k=0;k<c.targetTouches.length;++k)n=c.targetTouches[k],e[n.identifier].jb=!0;var m=n=Jb;F[m+4>>2]=c.ctrlKey;F[m+8>>2]=c.shiftKey;F[m+12>>2]=c.altKey;F[m+16>>2]=c.metaKey;m+=20;var u=a.getBoundingClientRect(),
tb=0;for(k in e){var w=e[k];F[m>>2]=w.identifier;F[m+4>>2]=w.screenX;F[m+8>>2]=w.screenY;F[m+12>>2]=w.clientX;F[m+16>>2]=w.clientY;F[m+20>>2]=w.pageX;F[m+24>>2]=w.pageY;F[m+28>>2]=w.Ya;F[m+32>>2]=w.jb;F[m+36>>2]=w.clientX-u.left;F[m+40>>2]=w.clientY-u.top;m+=52;if(32<=++tb)break}F[n>>2]=tb;W(d,f,n,b)&&c.preventDefault()},Na:c})}
function $b(a,b,c){var d=Ub[1];Ib||(Ib=h(8));U({target:d,Ma:"visibilitychange",Oa:c,Qa:function(b){b=b||event;var d=Ib,f=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);F[d>>2]=document.hidden;F[d+4>>2]=f;W(c,21,d,a)&&b.preventDefault()},Na:b})}var ac=1,bc=[],X=[],cc=[],dc=[],Y=[],ec=[],rb={},fc=null,gc={};function hc(a){for(var b=ac++,c=a.length;c<b;c++)a[c]=null;return b}var ic=[0];
function qb(a,b){if(a=a.getContext("webgl",b)){var c=h(8);b={handle:c,attributes:b,version:b.ab,Xa:a};a.canvas&&(a.canvas.mb=b);rb[c]=b;b=c}else b=0;return b}function sb(a){fc=rb[a];g.Ua=R=fc&&fc.Xa;return!(a&&!R)}var pb={},jc,kc,lc=["default","low-power","high-performance"],mc={};
function nc(){if(!oc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:"./this.program"},b;for(b in mc)a[b]=mc[b];var c=[];for(b in a)c.push(b+"="+a[b]);oc=c}return oc}var oc;function pc(a,b,c,d){for(var f=0;f<a;f++){var e=R[c](),k=e&&hc(d);e&&(e.name=k,d[k]=e);F[b+4*f>>2]=k}}
function qc(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=R.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=R.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof
Int32Array||d instanceof Array){for(a=0;a<d.length;++a)F[b+4*a>>2]=d[a];return}c=d.name|0}}F[b>>2]=c}}function rc(a,b,c,d,f){a-=5120;a=1==a?t:4==a?F:6==a?l:5==a||28922==a?za:ya;var e=31-Math.clz32(a.BYTES_PER_ELEMENT);return a.subarray(f>>e,f+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<e)+4-1&-4)>>e)}E("GMT",t,1957600,4);Ua=function(){return performance.now()};g.requestFullscreen=function(a,b,c){wb(a,b,c)};g.requestAnimationFrame=function(a){Za(a)};
g.setCanvasSize=function(a,b,c){yb(g.canvas,a,b);c||zb()};g.pauseMainLoop=function(){M=null;O++};g.resumeMainLoop=function(){O++;var a=Wa,b=Xa,c=L;L=null;$a(c,0,!1,ab,!0);Va(a,b);M()};g.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};g.createContext=function(a,b,c,d){return ob(a,b,c,d)};for(var R,sc=new Float32Array(256),Z=0;256>Z;Z++)ic[Z]=sc.subarray(0,Z+1);for(Z=0;256>Z;Z++);
var xc={ha:function(){window.setTimeout(aa,0)},T:function(a,b,c){window.setTimeout(fa,0,a,b,c)},$:function(){window.setTimeout(ba,0)},da:function(){window.setTimeout(ca,0)},W:function(a){window.setTimeout(da,0,a)},J:function(a){window.setTimeout(ea,0,a)},L:function(a){window.setTimeout(ha,0,a)},n:function(){},u:function(a,b){K=b;return 0},V:function(a,b){K=b;try{var c=D(Sa()),d=Sa(),f=Sa();return(void 0).open(c,d,f).sb}catch(e){return C(e),-e.Za}},U:function(a,b){K=b;return 0},m:function(){},O:function(){C()},
H:function(a,b){if(0===a)a=Date.now();else if(1===a)a=Ua();else return g.___errno_location&&(F[g.___errno_location()>>2]=28),-1;F[b>>2]=a/1E3|0;F[b+4>>2]=a%1E3*1E6|0;return 0},c:function(a,b,c){Pa.length=0;for(var d;d=t[b++];)100===d||102===d?(c=c+7&-8,Pa.push(Aa[c>>3]),c+=8):(c=c+3&-4,Pa.push(F[c>>2]),c+=4);return Oa[a].apply(null,Pa)},Aa:function(a,b,c,d){Cb(D(a),function(a){var d=h(a.length);t.set(a,d);tc(c,b,d,a.length);uc(d)},function(){d&&vc(d,b)})},I:function(a,b,c){a=V(a);if(!a)return-4;a=
a.getBoundingClientRect();Aa[b>>3]=a.width;Aa[c>>3]=a.height;return 0},M:function(a,b,c){t.set(t.subarray(b,b+c),a)},N:function(){C("OOM")},ma:function(a,b,c,d){Vb(a,b,c,d,12,"blur");return 0},la:function(a,b,c,d){Vb(a,b,c,d,13,"focus");return 0},ya:function(a,b,c,d){Wb(a,b,c,d,2,"keydown");return 0},xa:function(a,b,c,d){Wb(a,b,c,d,3,"keyup");return 0},ja:$a,wa:function(a,b,c,d){Xb(a,b,c,d,5,"mousedown");return 0},va:function(a,b,c,d){Xb(a,b,c,d,6,"mouseup");return 0},na:function(a,b,c,d){Yb(a,b,
c,d);return 0},sa:function(a,b,c,d){Zb(a,b,c,d,25,"touchcancel");return 0},ta:function(a,b,c,d){Zb(a,b,c,d,23,"touchend");return 0},ua:function(a,b,c,d){Zb(a,b,c,d,22,"touchstart");return 0},ka:function(a,b,c){$b(a,b,c);return 0},qa:function(a,b){var c={};b>>=2;c.alpha=!!F[b];c.depth=!!F[b+1];c.stencil=!!F[b+2];c.antialias=!!F[b+3];c.premultipliedAlpha=!!F[b+4];c.preserveDrawingBuffer=!!F[b+5];c.powerPreference=lc[F[b+6]];c.failIfMajorPerformanceCaveat=!!F[b+7];c.ab=F[b+8];c.wb=F[b+9];c.qb=F[b+10];
c.hb=F[b+11];c.yb=F[b+12];c.zb=F[b+13];a=V(a);return!a||c.hb?0:qb(a,c)},ra:function(a){a>>=2;for(var b=0;14>b;++b)F[a+b]=0;F[a]=F[a+1]=F[a+3]=F[a+4]=F[a+8]=F[a+10]=1},pa:function(a){return sb(a)?0:-5},P:function(a,b){var c=0;nc().forEach(function(d,f){var e=b+c;f=F[a+4*f>>2]=e;for(e=0;e<d.length;++e)va[f++>>0]=d.charCodeAt(e);va[f>>0]=0;c+=d.length+1});return 0},Q:function(a,b){var c=nc();F[a>>2]=c.length;var d=0;c.forEach(function(a){d+=a.length+1});F[b>>2]=d;return 0},v:function(a){wc(a)},t:function(){return 0},
R:function(a,b,c,d){try{var f=Ta.tb(a),e=Ta.pb(f,b,c);F[d>>2]=e;return 0}catch(k){return C(k),k.Za}},K:function(){return 0},S:function(a,b,c,d){try{for(var f=0,e=0;e<c;e++){for(var k=F[b+8*e>>2],r=F[b+(8*e+4)>>2],p=0;p<r;p++){var n=t[k+p],m=Ra[a];0===n||10===n?((1===a?ka:z)(ra(m,0)),m.length=0):m.push(n)}f+=r}F[d>>2]=f;return 0}catch(u){return C(u),u.Za}},A:function(a){R.activeTexture(a)},D:function(a,b){R.attachShader(X[a],ec[b])},ea:function(a,b,c){R.bindAttribLocation(X[a],b,D(c))},b:function(a,
b){R.bindBuffer(a,bc[b])},x:function(a,b){R.bindFramebuffer(a,cc[b])},z:function(a,b){R.bindTexture(a,dc[b])},ga:function(a,b){R.blendFunc(a,b)},f:function(a,b,c,d){R.bufferData(a,c?t.subarray(c,c+b):b,d)},q:function(a){R.clear(a)},r:function(a,b,c,d){R.clearColor(a,b,c,d)},E:function(a){R.compileShader(ec[a])},fa:function(){var a=hc(X),b=R.createProgram();b.name=a;X[a]=b;return a},G:function(a){var b=hc(ec);ec[b]=R.createShader(a);return b},w:function(a,b){for(var c=0;c<a;c++){var d=F[b+4*c>>2],
f=bc[d];f&&(R.deleteBuffer(f),f.name=0,bc[d]=null,d==jc&&(jc=0),d==kc&&(kc=0))}},X:function(a,b){for(var c=0;c<a;++c){var d=F[b+4*c>>2],f=cc[d];f&&(R.deleteFramebuffer(f),f.name=0,cc[d]=null)}},o:function(a){R.depthMask(!!a)},k:function(a){R.disable(a)},a:function(a,b,c){R.drawArrays(a,b,c)},p:function(a){R.enable(a)},ca:function(a){R.enableVertexAttribArray(a)},Y:function(a,b,c,d,f){R.framebufferTexture2D(a,b,c,dc[d],f)},g:function(a,b){pc(a,b,"createBuffer",bc)},Z:function(a,b){pc(a,b,"createFramebuffer",
cc)},C:function(a,b){pc(a,b,"createTexture",dc)},_:function(a,b){qc(a,b)},aa:function(a,b){b=D(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=gc[a]&&gc[a].fb[b])&&0<=c&&c<a[0]?a[1]+c:-1},ba:function(a){R.linkProgram(X[a]);var b=X[a];a=gc[a]={fb:{},bb:0,ub:-1,vb:-1};for(var c=a.fb,d=R.getProgramParameter(b,35718),f=0;f<d;++f){var e=R.getActiveUniform(b,f),k=e.name;a.bb=Math.max(a.bb,k.length+1);"]"==k.slice(-1)&&(k=k.slice(0,
k.lastIndexOf("[")));var r=R.getUniformLocation(b,k);if(r){var p=hc(Y);c[k]=[e.size,p];Y[p]=r;for(var n=1;n<e.size;++n)r=R.getUniformLocation(b,k+"["+n+"]"),p=hc(Y),Y[p]=r}}},ia:function(a,b,c,d){R.scissor(a,b,c,d)},F:function(a,b,c,d){for(var f="",e=0;e<b;++e){var k=d?F[d+4*e>>2]:-1;f+=D(F[c+4*e>>2],0>k?void 0:k)}R.shaderSource(ec[a],f)},y:function(a,b,c,d,f,e,k,r,p){R.texImage2D(a,b,c,d,f,e,k,r,p?rc(r,k,d,f,p):null)},l:function(a,b,c){R.texParameteri(a,b,c)},j:function(a,b){R.uniform1f(Y[a],b)},
B:function(a,b){R.uniform1i(Y[a],b)},d:function(a,b,c,d){if(256>=16*b)for(var f=ic[16*b-1],e=0;e<16*b;e+=16)f[e]=l[d+4*e>>2],f[e+1]=l[d+(4*e+4)>>2],f[e+2]=l[d+(4*e+8)>>2],f[e+3]=l[d+(4*e+12)>>2],f[e+4]=l[d+(4*e+16)>>2],f[e+5]=l[d+(4*e+20)>>2],f[e+6]=l[d+(4*e+24)>>2],f[e+7]=l[d+(4*e+28)>>2],f[e+8]=l[d+(4*e+32)>>2],f[e+9]=l[d+(4*e+36)>>2],f[e+10]=l[d+(4*e+40)>>2],f[e+11]=l[d+(4*e+44)>>2],f[e+12]=l[d+(4*e+48)>>2],f[e+13]=l[d+(4*e+52)>>2],f[e+14]=l[d+(4*e+56)>>2],f[e+15]=l[d+(4*e+60)>>2];else f=l.subarray(d>>
2,d+64*b>>2);R.uniformMatrix4fv(Y[a],!!c,f)},h:function(a){R.useProgram(X[a])},e:function(a,b,c,d,f,e){R.vertexAttribPointer(a,b,c,!!d,f,e)},s:function(a,b,c,d){R.viewport(a,b,c,d)},oa:function(a){a=new Date(1E3*F[a>>2]);F[489388]=a.getUTCSeconds();F[489389]=a.getUTCMinutes();F[489390]=a.getUTCHours();F[489391]=a.getUTCDate();F[489392]=a.getUTCMonth();F[489393]=a.getUTCFullYear()-1900;F[489394]=a.getUTCDay();F[489397]=0;F[489396]=0;F[489395]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/
864E5|0;F[489398]=1957600;return 1957552},memory:na,i:function(a){a=+a;return 0<=a?+Ja(a+.5):+Ia(a-.5)},table:oa,za:function(a){var b=Date.now()/1E3|0;a&&(F[a>>2]=b);return b}},yc=function(){function a(a){g.asm=a.exports;H--;0==H&&(null!==Ka&&(clearInterval(Ka),Ka=null),I&&(a=I,I=null,a()))}function b(b){a(b.instance)}function c(a){return Na().then(function(a){return WebAssembly.instantiate(a,d)}).then(a,function(a){z("failed to asynchronously prepare wasm: "+a);C(a)})}var d={env:xc,wasi_snapshot_preview1:xc};
H++;if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(f){return z("Module.instantiateWasm callback failed with error: "+f),!1}(function(){if("function"!==typeof WebAssembly.instantiateStreaming||La()||"function"!==typeof fetch)return c(b);fetch(J,{credentials:"same-origin"}).then(function(a){return WebAssembly.instantiateStreaming(a,d).then(b,function(a){z("wasm streaming compile failed: "+a);z("falling back to ArrayBuffer instantiation");c(b)})})})();return{}}();g.asm=yc;
var Qa=g.___wasm_call_ctors=function(){return(Qa=g.___wasm_call_ctors=g.asm.Ba).apply(null,arguments)};g._main=function(){return(g._main=g.asm.Ca).apply(null,arguments)};
var uc=g._free=function(){return(uc=g._free=g.asm.Da).apply(null,arguments)},q=g._Midi_FillBuffers=function(){return(q=g._Midi_FillBuffers=g.asm.Ea).apply(null,arguments)},h=g._malloc=function(){return(h=g._malloc=g.asm.Fa).apply(null,arguments)},ua=g.stackAlloc=function(){return(ua=g.stackAlloc=g.asm.Ga).apply(null,arguments)},tc=g.dynCall_viii=function(){return(tc=g.dynCall_viii=g.asm.Ha).apply(null,arguments)},vc=g.dynCall_vi=function(){return(vc=g.dynCall_vi=g.asm.Ia).apply(null,arguments)};
g.dynCall_v=function(){return(g.dynCall_v=g.asm.Ja).apply(null,arguments)};var W=g.dynCall_iiii=function(){return(W=g.dynCall_iiii=g.asm.Ka).apply(null,arguments)};g.asm=yc;var zc;function fb(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}I=function Ac(){zc||Bc();zc||(I=Ac)};
function Bc(a){a=a||ia;if(!(0<H||(Ca(Da),0<H||zc||(zc=!0,B)))){Ca(Ea);Ca(Fa);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(Cc){var b=g._main;a=a||[];var c=a.length+1,d=ua(4*(c+1));F[d>>2]=ta("./this.program");for(var f=1;f<c;f++)F[(d>>2)+f]=ta(a[f-1]);F[(d>>2)+c]=0;try{var e=b(c,d);wc(e,!0)}catch(k){if(!(k instanceof fb))if("unwind"==k)A=!0;else throw(b=k)&&"object"===typeof k&&k.stack&&(b=[k,k.stack]),z("exception thrown: "+b),k;}finally{}}Ca(Ha)}}g.run=Bc;
function wc(a,b){if(!b||!A||0!==a)throw A||(B=!0),new fb(a);}var Cc=!0;A=!0;Bc();


  return _FunkyKarts
}
)(typeof _FunkyKarts === 'object' ? _FunkyKarts : {});
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = _FunkyKarts;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return _FunkyKarts; });
    else if (typeof exports === 'object')
      exports["_FunkyKarts"] = _FunkyKarts;
    